# Generated by Django 6.0.3 on 2026-04-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('projects', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('technologies', models.IntegerField()),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('image', models.ImageField(upload_to='banner/')),
            ],
        ),
    ]
