# Generated by Django 6.0.3 on 2026-04-11 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0002_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('highlight_word', models.CharField(default='Best', max_length=50)),
                ('image', models.ImageField(upload_to='why/')),
            ],
        ),
        migrations.CreateModel(
            name='WhyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(upload_to='icons/')),
                ('whychoose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='myvetri.whychoose')),
            ],
        ),
    ]
