# Generated by Django 6.0.3 on 2026-04-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0003_whychoose_whypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='workprocess/')),
            ],
        ),
    ]
