# Generated by Django 6.0.3 on 2026-04-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0004_workprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(default=5)),
            ],
        ),
    ]
