# Generated by Django 6.0.3 on 2026-04-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0005_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
