# Generated by Django 6.0.3 on 2026-04-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0006_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
    ]
