# Generated by Django 6.0.3 on 2026-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='aboutus/')),
            ],
        ),
    ]
