# Generated by Django 6.0.3 on 2026-04-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0009_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vision_mission/')),
            ],
        ),
    ]
