# Generated by Django 6.0.3 on 2026-04-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0010_visionmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Web Development', max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='web/')),
            ],
        ),
    ]
