# Generated by Django 6.0.3 on 2026-04-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0011_webpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_stages/')),
            ],
        ),
    ]
