# Generated by Django 6.0.3 on 2026-04-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0013_staticsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dynamic_section/')),
            ],
        ),
    ]
