# Generated by Django 6.0.3 on 2026-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0014_dynamicsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcommerceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ecommerce_section/')),
            ],
        ),
    ]
