# Generated by Django 6.0.3 on 2026-04-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0016_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='software/')),
            ],
        ),
    ]
