# Generated by Django 6.0.3 on 2026-04-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0017_softwarepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeAppPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nativeapp/')),
            ],
        ),
    ]
