# Generated by Django 6.0.3 on 2026-04-16 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0019_hybridapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressiveWebApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pwa/')),
            ],
        ),
    ]
