# Generated by Django 6.0.3 on 2026-04-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0021_wearableembedded'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalMarketing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='digital_marketing/')),
            ],
        ),
    ]
