# Generated by Django 6.0.3 on 2026-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0022_digitalmarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='seo_images/')),
            ],
        ),
    ]
