# Generated by Django 6.0.3 on 2026-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0026_strategyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='google_analytics/')),
            ],
        ),
    ]
