# Generated by Django 6.0.3 on 2026-04-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0029_videomarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='google_ads/')),
            ],
        ),
    ]
