# Generated by Django 6.0.3 on 2026-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvetri', '0030_googleads'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
